# Generated by Django 2.0.7 on 2018-07-13 17:35

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('dt_created', models.DateTimeField(default=datetime.datetime(2018, 7, 13, 14, 35, 31, 275938))),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Usr_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_activity', models.ForeignKey(on_delete='DO_NOTHING', to='core.Activity')),
                ('fk_user', models.ForeignKey(on_delete='DO_NOTHING', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='users',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='core.Usr_activities'),
        ),
    ]
