# Generated by Django 2.0.7 on 2018-07-13 17:59

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='dt_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 14, 59, 37, 938210), verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.TimeField(null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Activity Name'),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='users',
        ),
        migrations.AddField(
            model_name='activity',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Related Users'),
        ),
        migrations.AlterField(
            model_name='usr_activities',
            name='fk_activity',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='core.Activity', verbose_name='Related Activity'),
        ),
        migrations.AlterField(
            model_name='usr_activities',
            name='fk_user',
            field=models.ForeignKey(on_delete='DO_NOTHING', to=settings.AUTH_USER_MODEL, verbose_name='Related User'),
        ),
    ]
